name: GitHub Release

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
      - "main"
    tags:
      - "v*"

  workflow_dispatch:

env:
  name: spatula

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Build release tarball
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          submodules: true
          path: code

      - name: Install tools
        run: sudo apt-get install pcregrep pandoc

      - name: Determine last tag via git describe
        if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
          else
            echo "tag=" >> "$GITHUB_ENV"
          fi
        working-directory: code

      # git describe does not return the current tag in tag pushes on GitHub Actions, use GITHUB_REF instead
      - name: Determine tag from GITHUB_REF
        if:  startsWith(github.ref, 'refs/tags/v')
        run: echo tag="$(echo "${GITHUB_REF}" | sed  -e 's/refs\/tags\///g')" >> "$GITHUB_ENV"

      - name: Write version change log
        run: .github/workflows/make-changelog-md.sh  "${tag:1}" | tee "${GITHUB_WORKSPACE}/changelog.md"
        working-directory: code

      - name: Copy source
        run: cp -R code "${name}-${tag:1}"

      - name: Remove .git
        run: rm -rf "${name}-${tag:1}/.git" && ls -laR "${name}-${tag:1}"

      - name: Tar source
        run: tar -cvzf "${name}-${tag:1}.tar.gz" "${name}-${tag:1}"

      - name: Tar source
        run: tar -cvJf "${name}-${tag:1}.tar.xz" "${name}-${tag:1}"

      - name: Tar source
        run: tar --zstd -cvf "${name}-${tag:1}.tar.xz" "${name}-${tag:1}"

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: release
          path: |
            *.tar.*
            changelog.md

  publish:
    name: Publish [GitHub]
    needs: [release]
    runs-on: ubuntu-24.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: release

      - name: Create release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: "*.tar.*"
          body_path: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
